name: CI
on:
  pull_request:
  push:
    branches-ignore: [master]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - run: sbt -J-Xmx3000m test